#!/usr/bin/env bash
# This script displays DNS A record info for subdomains

domain="$1"
subdomain="$2"

get_record() {
    sub="$1"
    ip=$(dig +short "$sub.$domain")
    if [[ -n "$ip" ]]; then
        echo "The subdomain $sub is a A record and points to $ip"
    fi
}

if [[ -z "$subdomain" ]]; then
    for sub in www lb-01 web-01 web-02; do
        get_record "$sub"
    done
else
    get_record "$subdomain"
fi
