#!/usr/bin/env bash

# Check number of arguments
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign variables
FILE=$1
IP=$2
USER=$3
KEY=$4

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE" "$USER@$IP:~/"
