#!/usr/bin/env bash

apt-get update
apt-get install -y nginx

# Update nginx conf to add the redirect
sed -i '/server_name _;/a \
    location /redirect_me { \
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    }' /etc/nginx/sites-available/default

# Restart nginx without systemctl
service nginx restart
