#!/usr/bin/env bash
# Sets up UFW to block all incoming traffic except 22, 80, 443

ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw enable
